'analytic_kl' argument has been removed
The analytic_kl argument seems has been removed from the declaration of "nvvae.NamedLatentVAE._build()" .
Remaining that argument in the train_nvvae.py will cause: 
''  File "/work/scott/tyao/sounds-deep/sounds_deep/contrib/experiments/train_nvvae.py", line 161, in <module>
    analytic_kl=True)
TypeError: _build() got an unexpected keyword argument 'analytic_kl''